dev_team: "2019 © Ruby Team."
validates:
  max_name: 50
  max_email: 255
  min_pass: 6
  max_content: 140
  max_address: 100
  valid_email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  max_company: 50
  max_alt: 20
  max_location: 255
  max_distance: 200
  max_age: 101
  max_description: 5000
zero: 0
cm: "(cm)"
kg: "(kg)"
km: "(km)"
validate:
  VALID_EMAIL_REGEX: !ruby/regexp '/\A[^@\s]+@[^@\s]+\z/'
fb: "Facebook"
gg: "Google"
gender:
  male: "male"
  female: "female"
  both: "both"
reaction:
  like: "like"
  dislike: "dislike"
  block: "block"
noti_key:
  like: "like"
  dislike: "dislike"
  match: "match"
  unblock: "unblock"
page:
  one: 1
size:
  zero: 0
page: 6
